Verify presentation timestamp is within request request interval
hyperledger/anoncreds-rs pull request #49
Opened 2023-01-06 15:01 UTC by whalelephant

Closes #41 

(pending discussion outcome)

2023-01-10 09:29 UTC, TimoGlastra reviewed
It's great that we're expanding the return type of the verify proof method. However, I'm not a fan of keep the default isVerified `true` and seeing the NRP as a warning. If there's a proof request with a certain requirement, and that requirement is not met, is the proof still valid? Some parts may be, but I'm not sure if we should return a single boolean in that case. It's making it too easy to mess things up, and can give the wrong impression.

I quite like how Trinsic has solved this issue in their API, and maybe we can make it similair to this. The structure of their verify proof call looks like this:

```json
{
  "is_valid": true,
  "validation_results": {
    "SignatureVerification": {
        "is_valid": true,
         "messages": [],
    },
    "CredentialStatus": {
        "is_valid": true,
         "messages": [],
    },
    "SchemaConformance": {
        "is_valid": true,
         "messages": [],
    },
    "TrustRegistryMembership": {
        "is_valid": true,
         "messages": [],
    },
    "IssuerIsSigner": {
        "is_valid": true,
         "messages": [],
    },
  }
}
```

Each of the `validation_results` referes to a separate validation step that is taken. Only if all `validation_results.is_valid` evaluate to `true`, the top level `is_valid` is true. 

In this case the `SignatureVerification` will be valid, but the `CredentialStatus` (or whatever we want to call it in AnonCreds) is not valid according to the proof request.

cc @swcurran

2023-01-10 22:04 UTC, swcurran commented
In general I like that. However, the problem I'm highlighting with the interval is that we don't (and, I would argue) can't know if the interval requirement has been satisfied for the reasons given on the other issue.  If both parties had a list of all of the RevocationStatusList entry timestamps, it would be possible, but I think there will be too many occasions when a verification will be incorrectly flagged as false because, the timestamp used is outside of the interval.   I think we should look for a better solution in V2.0, but in v1.0, I think it is tricky.

To be precise -- if a verifier gives the interval '{ "from": "now()", "to": "now()" }`, as we currently recommend that verifiers do, the presentation will always be invalid (unless of course, the issuer happens to publish a new revocation registry at exactly "now()"). The holder creating an NRP based on the RevocationStatusList entry immediately before the interval is technically "within the interval", but that is very difficult for the AnonCreds verifier code to check. 

The semantics of interval are too complex to properly implement if there is no way to query the ledger to know what timestamped transactions are within the interval.

2023-01-11 08:20 UTC, blu3beri requested changes
Couple of smaller things, but overall looks good! I am not too familiar with the spec and the correctness of the implementation, so the review is mainly about the code.

2023-01-11 08:20 UTC, blu3beri commented on anoncreds/src/data_types/anoncreds/rev_reg.rs
> +            }
```suggestion
            Self::default()
```

2023-01-11 08:20 UTC, blu3beri commented on anoncreds/src/services/verifier.rs
> +                    .ok_or_else(|| err_msg!("Referent validation failed: {}", referent))
```suggestion
                    .ok_or_else(|| err_msg!("Referent validation failed: {referent}"))
```

I believe clippy complains about this now.

2023-01-11 08:20 UTC, blu3beri commented on anoncreds/src/services/verifier.rs
> +
Would it be worth it to instantiate a new one, shadowing the previous one, and keeping `timestamps_out_of_range` private? Not sure if it would work.

2023-01-11 08:20 UTC, blu3beri commented on anoncreds/src/services/verifier.rs
> +// a wanring is provided for the verifier to decide if they will reject the proof or not
```suggestion
// a warning is provided for the verifier to decide if they will reject the proof or not
```

2023-01-11 08:20 UTC, blu3beri commented on anoncreds/src/services/verifier.rs
> +                warnings.push(referent.to_string());
Very nit picky but I prefer `to_owned` as it descibes the intention a bit better.

2023-01-11 08:20 UTC, blu3beri commented on anoncreds/src/services/verifier.rs
> +        Ok(())
```suggestion
        } else {
            Err(err_msg!("Missing timestamp"))
        }
    Ok(())
```


That would work, right?

2023-01-11 08:20 UTC, blu3beri commented on anoncreds/src/services/verifier.rs
> +                schema_id: SchemaId::default(),
Huh, did not know I implemented default for the anoncreds ids. Ah, could be nice for testing :).

2023-01-11 10:09 UTC, TimoGlastra commented
> In general I like that. However, the problem I'm highlighting with the interval is that we don't (and, I would argue) can't know if the interval requirement has been satisfied for the reasons given on the other issue. If both parties had a list of all of the RevocationStatusList entry timestamps, it would be possible, but I think there will be too many occasions when a verification will be incorrectly flagged as false because, the timestamp used is outside of the interval. I think we should look for a better solution in V2.0, but in v1.0, I think it is tricky.
> 
> To be precise -- if a verifier gives the interval '{ "from": "now()", "to": "now()" }`, as we currently recommend that verifiers do, the presentation will always be invalid (unless of course, the issuer happens to publish a new revocation registry at exactly "now()"). The holder creating an NRP based on the RevocationStatusList entry immediately before the interval is technically "within the interval", but that is very difficult for the AnonCreds verifier code to check.
> 
> The semantics of interval are too complex to properly implement if there is no way to query the ledger to know what timestamped transactions are within the interval.

Makes sense. I misunderstood the issue. So what we should actually check is whether the timestamp that the proof is based on, is the most accurate based on the proof request? So If I request `now()` and that evaluates to 200, and there's two timestamps available `10` and `190`, we should pick `190`. If there's `10`, `190`, and `210` we should pick either `190` and `210`? 

I still think we should be careful in seeing this as a warning. Ideally we let the verifier provide the closest 'state' (and thus the one that matches with the one the holder provided -- if all is good). This could be tricked however as currently you just provide a map of revocation registries, with the timestamps as keys. Multiple timestamps could be present for the same reovcatino registry for different parts of the proof.  The verifier would need to provide the revocation registry with timestamp per group in the request, so we can throw an error if the revocation registry timestamp the holder used does not match with the revocation registry timestamp the verifier expects the holder to use for a given timeframe

The steps for the verifier when receiving a proof will be:
1. Extract the timestamp the holder used for a specific group name / credential from the proof
2. Fetch the revocation state at the given timestamp from the ledger
3. If the timestamp is within the revocation interval all good and use the revocation registry in the verify method
4. If the timestamp is not within the revocation interval, check if the timestamp the holder used to create the proof is the most logical based on available updates to the ledger. Or, just accept the timestamp the user provided, if you're willing to accept it.

Which of these steps are to be peformed by the upper level vs AnonCreds I'm not sure, but we should maybe add wording to the spec to note these edge cases?

2023-01-11 19:58 UTC, swcurran commented
Regards from @TimoGlastra:

> Which of these steps are to be performed by the upper level vs AnonCreds I'm not sure, but we should maybe add wording to the spec to note these edge cases?

I suggest that we do exactly what is in the implementation today (since that is what v1.0 of the specification is intending -- and we're only making changes for ledger-agnosticism and clarification), and we document (as you say) the rough edges in the 1.0 specification.  The problem we have today is that there is not a good way to query the ledger to determine the edges of the interval.

An idea for a what might be a relatively easy clean up is that we update the AnonCreds methods to add to the `resolve_RevReg(revRegId)` response some extra data -- "previous_timestamp", "next_timestamp" (and perhaps "latest_timestamp") so that the verifier can determine if the NRP meets the interval requirement.  Not for today, but perhaps in the next version?

2023-01-17 07:08 UTC, TimoGlastra commented
Have thought about it more, and also discussed this with @whalelephant. I do not agree we should return that the proof is verified. If the timestamp is outside of the requested revocation interval extra processing is required by the verifier to determine if it would like to accept the submitted timestamp (based on how close it is to the requested interval, or what timestamps are available on the ledger).

So I'll still like to suggest we return isVerifeid is false, and we add the context object with true/false for each of the specific checks that has been done.  We can then inform the user of this library that if the proof falls outside of the revocation interval, it means all checks will be true, except for one. If that is the case, the verifier can do some additional checks and still see it as valid, but by default I would say it is not valid. If people see isValid=false they'll dig into why it is invalid, if it is true, they'll won't look further

2023-01-17 15:06 UTC, swcurran commented
How does that approach compare with what is done in the indy-sdk and credx?

2023-01-17 15:32 UTC, swcurran commented
This change will break any verifiers that followed the "Best Practices" from Aries by using the same value for `to` and `from` and did not search for a valid timestamp.  AFAIK, most verifiers use `now()` for those two values, and this change will mean that all of those presentations will fail validation.

2023-01-17 16:36 UTC, TimoGlastra commented
Anoncreds rs is a library, and it's still up to the code/framework that is calling this library how to interpret the result.

Maybe it'll force people that update to anoncreds rs to reconsider their current implementstion, or in ACA-Py we could still choose to see it as valid. What is important is that we don't see it as valid by default and let it to the user of this library to decide whether they would like to accept this use case. Maybe it'll break some flows that used to work, but if any timestamp was accepted before it means we now have improved security.

2023-01-17 16:38 UTC, TimoGlastra commented
> or in ACA-Py we could still choose to see it as valid.

This is the main point of my comment. AnonCreds is just a library that gives context. ACA-Py decides how to interpret that context.

2023-01-17 22:39 UTC, swcurran commented
Let's discuss on Monday in person.  

Still interested to know this:  How does that approach compare with what is done in the indy-sdk and credx?

I'm also interested to know -- if the latest RevStatusList entry is at time T and that is timestamp used by the holder, and the interval time from the verifier was `{From, to = T+t}`, would the approach you are proposing say "verified" or "not verified"?  The correct answer is "verified", but I don't think AnonCreds has enough information to know that.

For the discuss on Monday, I propose that we leave interval as is for v1.0, and we define a new approach for requesting/verifying revocation in the next release.

2023-02-24 16:53 UTC, whalelephant commented
Addressed in #102

2023-02-24 16:53 UTC, closed without merging